// Users API: a Retrofit interface over Dio (users_api.g.dart is generated by retrofit_generator).
// Plain app code, no interception/proxy code of any kind.
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '../models/todo.dart';
import '../models/user.dart';

part 'users_api.g.dart';

@RestApi(baseUrl: 'https://jsonplaceholder.typicode.com')
abstract class UsersApi {
  factory UsersApi(Dio dio, {String? baseUrl}) = _UsersApi;

  @GET('/users/{id}')
  Future<HttpResponse<User>> getUser(@Path('id') int id);

  @GET('/users/{id}/todos')
  Future<List<Todo>> getTodos(@Path('id') int userId);
}
