import type { Exchange } from '@flutter-intercept/proxy';
import { describe, expect, it } from 'vitest';
import type { ApiEndpoint } from '../../src/contract/types';
import { generateFixtureTest, matchEndpoint } from '../../src/codegen/fixtures';
import type { FixtureApi } from '../../src/codegen/types';

let seq = 0;
function ex(method: string, url: string, status: number | undefined, body?: string | { b64: string }, extra: Partial<Exchange> = {}): Exchange {
  return {
    id: String(++seq),
    startedAt: 0,
    method,
    url,
    requestHeaders: {},
    status,
    responseHeaders: { 'content-type': 'application/json' },
    responseBody: body === undefined ? undefined : typeof body === 'string' ? { text: body, encoding: 'utf8' } : { text: body.b64, encoding: 'base64' },
    state: status === undefined ? 'error' : 'completed',
    ...extra,
  };
}

const SMALL = () => [
  ex('GET', 'https://api.example.com/users/42', 200, '{"id":42,"token":"[redacted]"}'),
  ex('POST', 'https://api.example.com/users', 500, 'oops', {
    requestBody: { text: '{"name":"a"}', encoding: 'utf8' },
    responseHeaders: { 'content-type': 'text/plain' },
  }),
];
const FIXTURES = [
  { path: 'test/fixtures/get_user_1.json', content: '{\n  "id": 42,\n  "token": "[redacted]"\n}\n' },
  { path: 'test/fixtures/get_user_2.json', content: '"oops"\n' },
];

const DIO_ADAPTER = [
  "// Generated by Flutter Intercept from 2 recorded exchanges.",
  "// Bodies are redacted: \"[redacted]\" marks a value that held a secret.",
  "",
  "import 'dart:convert';",
  "import 'dart:io';",
  "",
  "import 'package:dio/dio.dart';",
  "import 'package:flutter_test/flutter_test.dart';",
  "import 'package:http_mock_adapter/http_mock_adapter.dart';",
  "",
  "/// A recorded body from test/fixtures (tests run from the package root).",
  "dynamic fixture(String name) =>",
  "    jsonDecode(File('test/fixtures/$name').readAsStringSync());",
  "",
  "void main() {",
  "  late Dio dio;",
  "  late DioAdapter adapter;",
  "",
  "  setUp(() {",
  "    // Every status is a response here, so error bodies can be checked too.",
  "    dio = Dio(BaseOptions(validateStatus: (_) => true));",
  "    adapter = DioAdapter(dio: dio);",
  "  });",
  "",
  "  test('GET /users/42 → 200', () async {",
  "    const url = 'https://api.example.com/users/42';",
  "    final body = fixture('get_user_1.json');",
  "    adapter.onGet(",
  "      url,",
  "      (server) => server.reply(200, body),",
  "    );",
  "",
  "    final response = await dio.get<dynamic>(url);",
  "",
  "    expect(response.statusCode, 200);",
  "    expect(response.data, body);",
  "  });",
  "",
  "  test('POST /users → 500', () async {",
  "    const url = 'https://api.example.com/users';",
  "    final body = fixture('get_user_2.json');",
  "    adapter.onPost(",
  "      url,",
  "      (server) => server.reply(500, body, headers: {Headers.contentTypeHeader: ['text/plain']}),",
  "      data: Matchers.any,",
  "    );",
  "",
  "    final response = await dio.post<dynamic>(",
  "      url,",
  "      data: r'''{\"name\":\"a\"}''',",
  "    );",
  "",
  "    expect(response.statusCode, 500);",
  "    expect(response.data, body);",
  "  });",
  "}",
  ""
].join('\n');

const MOCK_CLIENT = [
  "// Generated by Flutter Intercept from 2 recorded exchanges.",
  "// Bodies are redacted: \"[redacted]\" marks a value that held a secret.",
  "",
  "import 'dart:convert';",
  "import 'dart:io';",
  "",
  "import 'package:flutter_test/flutter_test.dart';",
  "import 'package:http/http.dart';",
  "import 'package:http/testing.dart';",
  "",
  "/// A recorded body from test/fixtures (tests run from the package root).",
  "dynamic fixture(String name) =>",
  "    jsonDecode(File('test/fixtures/$name').readAsStringSync());",
  "",
  "void main() {",
  "  test('GET /users/42 → 200', () async {",
  "    const url = 'https://api.example.com/users/42';",
  "    final body = fixture('get_user_1.json');",
  "    // Inject `client` (an http.Client) into the code under test instead of calling it here.",
  "    final client = MockClient((request) async {",
  "      expect(request.method, 'GET');",
  "      expect(request.url, Uri.parse(url));",
  "      return Response.bytes(",
  "        utf8.encode(jsonEncode(body)),",
  "        200,",
  "        headers: {'content-type': 'application/json; charset=utf-8'},",
  "      );",
  "    });",
  "",
  "    final response = await client.get(Uri.parse(url));",
  "",
  "    expect(response.statusCode, 200);",
  "    expect(jsonDecode(response.body), body);",
  "  });",
  "",
  "  test('POST /users → 500', () async {",
  "    const url = 'https://api.example.com/users';",
  "    final body = fixture('get_user_2.json');",
  "    // Inject `client` (an http.Client) into the code under test instead of calling it here.",
  "    final client = MockClient((request) async {",
  "      expect(request.method, 'POST');",
  "      expect(request.url, Uri.parse(url));",
  "      return Response.bytes(",
  "        utf8.encode(body as String),",
  "        500,",
  "        headers: {'content-type': 'text/plain; charset=utf-8'},",
  "      );",
  "    });",
  "",
  "    final response = await client.post(",
  "      Uri.parse(url),",
  "      body: r'''{\"name\":\"a\"}''',",
  "    );",
  "",
  "    expect(response.statusCode, 500);",
  "    expect(response.body, body);",
  "  });",
  "}",
  ""
].join('\n');

describe('generateFixtureTest (golden)', () => {
  it('http_mock_adapter', () => {
    expect(generateFixtureTest({ exchanges: SMALL(), style: 'http_mock_adapter', name: 'get_user' })).toEqual([
      ...FIXTURES,
      { path: 'test/get_user_test.dart', content: DIO_ADAPTER },
    ]);
  });
  it('mock_client', () => {
    expect(generateFixtureTest({ exchanges: SMALL(), style: 'mock_client', name: 'get_user' })).toEqual([
      ...FIXTURES,
      { path: 'test/get_user_test.dart', content: MOCK_CLIENT },
    ]);
  });
});

describe('generateFixtureTest', () => {
  const testFile = (files: { path: string; content: string }[]) => files[files.length - 1].content;

  it('keeps JSON literals byte-faithful and [redacted] visible', () => {
    const [f] = generateFixtureTest({ exchanges: [ex('GET', 'https://a.dev/x', 200, '{"price":1.0,"big":12345678901234567890,"s":"[redacted]"}')], style: 'mock_client', name: 'x' });
    expect(f.content).toBe('{\n  "price": 1.0,\n  "big": 12345678901234567890,\n  "s": "[redacted]"\n}\n');
  });

  it('turns binary, non-JSON and truncated bodies into string fixtures', () => {
    const files = generateFixtureTest({
      exchanges: [
        ex('GET', 'https://a.dev/img', 200, { b64: Buffer.from([1, 2, 3]).toString('base64') }),
        ex('GET', 'https://a.dev/page', 200, '<p>"hi"</p>', { responseHeaders: { 'Content-Type': 'text/html' } }),
        ex('GET', 'https://a.dev/big', 200, '{"a":[1,2', { responseBody: { text: '{"a":[1,2', encoding: 'utf8', truncated: true } }),
      ],
      style: 'http_mock_adapter',
      name: 'misc',
    });
    expect(files.slice(0, 3).map((f) => f.content)).toEqual(['"[binary 3 bytes]"\n', '"<p>\\"hi\\"</p>"\n', '"{\\"a\\":[1,2"\n']);
    const t = testFile(files);
    expect(t).toContain('// The response body is binary: the fixture only says how big it was.');
    expect(t).toContain('// The response body was truncated when it was recorded (larger than 5 MB).');
    expect(t).toContain("server.reply(200, body, headers: {Headers.contentTypeHeader: ['text/html']})");
  });

  it('skips exchanges without a response, numbers fixtures by position, and labels repeats', () => {
    const files = generateFixtureTest({
      exchanges: [
        ex('GET', 'https://a.dev/x', undefined, undefined, { error: 'connect ECONNREFUSED\nmore' }),
        ex('GET', 'https://a.dev/x', 200, '{}'),
        ex('DELETE', 'https://a.dev/x', 204),
        ex('GET', 'https://a.dev/x', 200, '[]'),
      ],
      style: 'mock_client',
      name: 'Get X',
    });
    expect(files.map((f) => f.path)).toEqual(['test/fixtures/get_x_2.json', 'test/fixtures/get_x_4.json', 'test/get_x_test.dart']);
    const t = testFile(files);
    expect(t).toContain('  // Not included: GET /x has no response (error: connect ECONNREFUSED more).');
    expect(t).toContain("test('GET /x → 200 (#2)'");
    expect(t).toContain("test('DELETE /x → 204', () async {\n    const url = 'https://a.dev/x';\n    // Inject");
    expect(t).toContain('        <int>[],\n        204,\n      );');
  });

  it('escapes $ and quotes in URLs and labels', () => {
    const t = testFile(generateFixtureTest({ exchanges: [ex('GET', "https://a.dev/s?q=$5&n=it's", 200, '{}')], style: 'mock_client', name: 's' }));
    expect(t).toContain("test('GET /s?q=\\$5&n=it%27s → 200'");
    expect(t).toContain("const url = 'https://a.dev/s?q=\\$5&n=it\\'s';");
  });

  it('http_mock_adapter: comments out methods it cannot mock; mock_client sends them as a Request', () => {
    const exchanges = [ex('OPTIONS', 'https://a.dev/x', 204)];
    expect(testFile(generateFixtureTest({ exchanges, style: 'http_mock_adapter', name: 'o' }))).toContain("// Not included: http_mock_adapter can't mock OPTIONS (OPTIONS /x → 204).");
    expect(testFile(generateFixtureTest({ exchanges, style: 'mock_client', name: 'o' }))).toContain(
      "    final request = Request('OPTIONS', Uri.parse(url));\n    final response = await Response.fromStream(await client.send(request));",
    );
  });

  it('emits a skipped test when nothing had a response, and supports package:test', () => {
    const t = testFile(generateFixtureTest({ exchanges: [ex('GET', 'https://a.dev/x', undefined)], style: 'mock_client', name: 'x', testPackage: 'test' }));
    expect(t).toContain("import 'package:test/test.dart';");
    expect(t).toContain("skip: 'none of the exchanges had a response'");
  });
});

describe('mocktail (Retrofit interface)', () => {
  const ep = (method: string, pathTemplate: string, dartMethod: string, extra: Partial<ApiEndpoint> = {}): ApiEndpoint => ({
    method,
    pathTemplate,
    dartMethod,
    file: '/app/lib/api/user_api.dart',
    line: 1,
    ...extra,
  });
  const API: FixtureApi = {
    className: 'UserApi',
    imports: ['package:app/api/user_api.dart', 'package:app/models/user.dart'],
    endpoints: [
      ep('GET', 'https://api.example.com/users/{id}', 'getUser', { params: [{ name: 'id', type: 'int', kind: 'path' }], returnType: 'Future<User>' }),
      ep('GET', '/users', 'listUsers', { params: [{ name: 'page', type: 'int?', kind: 'query', named: true }], returnType: 'Future<List<User>>' }),
      ep('POST', '/users', 'createUser', { params: [{ name: 'user', type: 'User', kind: 'body' }], returnType: 'Future<HttpResponse<User>>' }),
      ep('DELETE', '/users/{id}', 'deleteUser', { params: [{ name: 'id', type: 'int', kind: 'path' }], returnType: 'Future<void>' }),
      ep('GET', '/users/{id}/raw', 'raw', { params: [{ name: 'id', type: 'String', kind: 'path' }, { name: 'trace', type: 'String?', kind: 'header' }] }),
    ],
  };
  const gen = (exchanges: Exchange[], api: FixtureApi | null = API, packageName?: string) =>
    generateFixtureTest({ exchanges, style: 'mocktail', name: 'users', api: api ?? undefined, packageName }).at(-1)!.content;

  it('stubs the matching method with the fixture decoded into its return type', () => {
    const t = gen([ex('GET', 'https://api.example.com/users/42', 200, '{"id":42}')]);
    expect(t).toContain('class MockUserApi extends Mock implements UserApi {}');
    expect(t).toContain("import 'package:app/models/user.dart';");
    expect(t).toContain(
      [
        "  test('getUser: GET /users/42 → 200', () async {",
        "    final body = fixture('users_1.json');",
        '    final value = User.fromJson(body as Map<String, dynamic>);',
        '    when(() => api.getUser(any())).thenAnswer((_) async => value);',
        '',
        '    // Use `api` in the code under test instead of calling it here.',
        '    final result = await api.getUser(42);',
        '',
        '    expect(result, value);',
        '    verify(() => api.getUser(any())).called(1);',
        '  });',
      ].join('\n'),
    );
    expect(t).not.toContain('package:dio');
  });

  it('handles named query params, lists, HttpResponse, body params (with a fallback value) and void', () => {
    const t = gen([
      ex('GET', 'https://api.example.com/users?page=2', 200, '[{"id":1}]'),
      ex('POST', 'https://api.example.com/users', 201, '{"id":3}', { requestBody: { text: '{"name":"n"}', encoding: 'utf8' } }),
      ex('DELETE', 'https://api.example.com/users/3', 204),
    ]);
    expect(t).toContain("when(() => api.listUsers(page: any(named: 'page'))).thenAnswer((_) async => value);");
    expect(t).toContain('final result = await api.listUsers(page: 2);');
    expect(t).toContain('(body as List<dynamic>).map((e) => User.fromJson(e as Map<String, dynamic>)).toList()');
    expect(t).toContain('HttpResponse(User.fromJson(body as Map<String, dynamic>), Response(requestOptions: RequestOptions(path: url), statusCode: 201, data: body))');
    expect(t).toContain("await api.createUser(User.fromJson(jsonDecode(r'''{\"name\":\"n\"}''') as Map<String, dynamic>));");
    expect(t).toContain('class _FakeUser extends Fake implements User {}');
    expect(t).toContain('registerFallbackValue(_FakeUser());');
    expect(t).toContain("import 'package:retrofit/retrofit.dart';");
    expect(t).toContain('when(() => api.deleteUser(any())).thenAnswer((_) async {});');
    expect(t).toContain('    await api.deleteUser(3);\n');
    expect(t).not.toContain('const dynamic body');
  });

  it('turns non-2xx responses into the DioException Retrofit throws', () => {
    const t = gen([ex('GET', 'https://api.example.com/users/9', 404, '{"error":"nope"}')]);
    expect(t).toContain("import 'package:dio/dio.dart';");
    expect(t).toContain('      (_) async => throw DioException(');
    expect(t).toContain('          statusCode: 404,\n          data: body,');
    expect(t).toContain("isA<DioException>().having((e) => e.response?.statusCode, 'status', 404)");
    expect(t).toContain('      api.getUser(9),');
  });

  it('passes the fixture as dynamic when the return type is unknown, and null for nullable headers', () => {
    const t = gen([ex('GET', 'https://api.example.com/users/a%20b/raw', 200, 'text', { responseHeaders: { 'content-type': 'text/plain' } })]);
    expect(t).toContain('    final value = body;\n');
    expect(t).toContain("    await api.raw('a b', null);\n");
    expect(t).not.toContain('final result');
  });

  it('comments out requests no method matches', () => {
    const t = gen([ex('GET', 'https://api.example.com/users/1', 200, '{}'), ex('GET', 'https://cdn.example.com/x.png', 200, '{}')]);
    expect(t).toContain('// Not included: no UserApi method with a known signature matches GET /x.png → 200.');
  });

  it('falls back to MockClient without an interface, without parameters, or without any match', () => {
    const exchanges = [ex('GET', 'https://api.example.com/users/1', 200, '{}')];
    const none = gen(exchanges, null);
    expect(none).toContain('// mocktail needs the Retrofit interface to mock, but no Retrofit interface was found for these requests:');
    expect(none).toContain('final client = MockClient(');
    const bare = gen(exchanges, { className: 'UserApi', endpoints: [ep('GET', '/users/{id}', 'getUser', { responseModel: 'User' })] });
    expect(bare).toContain("but the parameters of UserApi's methods are unknown:");
    const miss = gen([ex('GET', 'https://other.dev/a', 200, '{}')]);
    expect(miss).toContain('but no UserApi method matches these requests:');
  });

  it('imports the endpoints\' importUri when no imports are given', () => {
    const api: FixtureApi = {
      className: 'UserApi',
      endpoints: [ep('GET', '/users/{id}', 'getUser', { importUri: 'package:app/api/users_api.dart', params: [{ name: 'id', type: 'int', kind: 'path' }] })],
    };
    const t = gen([ex('GET', 'https://api.example.com/users/1', 200, '{}')], api);
    expect(t).toContain("import 'package:app/api/users_api.dart';");
    expect(t).toContain('// Also import the models its methods return.');
  });

  it('derives the interface import from its file and the package name', () => {
    const api: FixtureApi = { className: 'UserApi', endpoints: [ep('GET', '/users/{id}', 'getUser', { params: [{ name: 'id', type: 'int', kind: 'path' }] })] };
    const t = gen([ex('GET', 'https://api.example.com/users/1', 200, '{}')], api, 'app');
    expect(t).toContain("import 'package:app/api/user_api.dart';");
    expect(t).toContain('// Also import the models its methods return.');
  });
});

describe('matchEndpoint', () => {
  const e = (method: string, pathTemplate: string, dartMethod: string): ApiEndpoint => ({ method, pathTemplate, dartMethod, file: 'f', line: 1 });
  const eps = [e('GET', '/users/{id}', 'byId'), e('GET', '/users/me', 'me'), e('GET', 'https://api.x.dev/v1/users/{id}', 'abs'), e('POST', '/users/{id}', 'post')];

  it('prefers absolute templates, then the most literal one', () => {
    expect(matchEndpoint(eps, 'GET', 'https://api.x.dev/v1/users/7')?.endpoint.dartMethod).toBe('abs');
    expect(matchEndpoint(eps, 'GET', 'https://other.dev/users/me')?.endpoint.dartMethod).toBe('me');
    expect(matchEndpoint(eps, 'get', 'https://other.dev/api/users/7?x=1')?.endpoint.dartMethod).toBe('byId');
    expect(matchEndpoint(eps, 'POST', 'https://other.dev/users/7')?.pathValues.get('id')).toBe('7');
  });

  it('needs the same method and a full path match', () => {
    expect(matchEndpoint(eps, 'PUT', 'https://a.dev/users/7')).toBeUndefined();
    expect(matchEndpoint(eps, 'GET', 'https://a.dev/users/7/posts')).toBeUndefined();
    expect(matchEndpoint(eps, 'GET', 'https://a.dev/xusers/7')).toBeUndefined();
    expect(matchEndpoint(eps, 'GET', 'not a url')).toBeUndefined();
  });
});
