import { describe, expect, it } from 'vitest';
import { parseJsonSample } from '../../src/codegen/json';
import { decode, encode, generateModels } from '../../src/codegen/models';
import type { ModelStyle } from '../../src/codegen/types';

const SAMPLES = ['{"id":1,"avatar_url":"a","bio":"x","price":2,"tags":[],"address":{"city":"c"}}', '{"id":2,"avatar_url":null,"price":2.5,"tags":["t"],"address":{"city":"d"}}'];
const SOURCE = 'GET https://api.example.com/users/{id}';
const gen = (style: ModelStyle, samples = SAMPLES, rootName = 'user', source: string | null = SOURCE) =>
  generateModels({ samples: samples.map(parseJsonSample), rootName, style, source: source ?? undefined });

const FREEZED = String.raw`// Generated by Flutter Intercept from 2 recorded responses
// of GET https://api.example.com/users/{id}.
// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'user.freezed.dart';
part 'user.g.dart';

@freezed
abstract class User with _$User {
  @JsonSerializable(explicitToJson: true)
  const factory User({
    required int id,

    /// null in some samples.
    @JsonKey(name: 'avatar_url') String? avatarUrl,

    /// Missing from some samples.
    @JsonKey(includeIfNull: false) String? bio,
    required double price,
    required List<String> tags,
    required Address address,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}

@freezed
abstract class Address with _$Address {
  const factory Address({required String city}) = _Address;

  factory Address.fromJson(Map<String, dynamic> json) =>
      _$AddressFromJson(json);
}
`;

const JSON_SERIALIZABLE = String.raw`// Generated by Flutter Intercept from 2 recorded responses
// of GET https://api.example.com/users/{id}.

import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable(explicitToJson: true)
class User {
  const User({
    required this.id,
    this.avatarUrl,
    this.bio,
    required this.price,
    required this.tags,
    required this.address,
  });

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  final int id;

  /// null in some samples.
  @JsonKey(name: 'avatar_url')
  final String? avatarUrl;

  /// Missing from some samples.
  @JsonKey(includeIfNull: false)
  final String? bio;

  final double price;
  final List<String> tags;
  final Address address;

  Map<String, dynamic> toJson() => _$UserToJson(this);
}

@JsonSerializable()
class Address {
  const Address({required this.city});

  factory Address.fromJson(Map<String, dynamic> json) =>
      _$AddressFromJson(json);

  final String city;

  Map<String, dynamic> toJson() => _$AddressToJson(this);
}
`;

const PLAIN = String.raw`// Generated by Flutter Intercept from 2 recorded responses
// of GET https://api.example.com/users/{id}.

class User {
  const User({
    required this.id,
    this.avatarUrl,
    this.bio,
    required this.price,
    required this.tags,
    required this.address,
  });

  factory User.fromJson(Map<String, dynamic> json) => User(
    id: json['id'] as int,
    avatarUrl: json['avatar_url'] as String?,
    bio: json['bio'] as String?,
    price: (json['price'] as num).toDouble(),
    tags: (json['tags'] as List<dynamic>).map((e) => e as String).toList(),
    address: Address.fromJson(json['address'] as Map<String, dynamic>),
  );

  final int id;

  /// null in some samples.
  final String? avatarUrl;

  /// Missing from some samples.
  final String? bio;

  final double price;
  final List<String> tags;
  final Address address;

  Map<String, dynamic> toJson() => {
    'id': id,
    'avatar_url': avatarUrl,
    if (bio != null) 'bio': bio,
    'price': price,
    'tags': tags,
    'address': address.toJson(),
  };
}

class Address {
  const Address({required this.city});

  factory Address.fromJson(Map<String, dynamic> json) =>
      Address(city: json['city'] as String);

  final String city;

  Map<String, dynamic> toJson() => {'city': city};
}
`;

describe('generateModels (golden)', () => {
  it('freezed 3', () => {
    expect(gen('freezed')).toEqual([{ path: 'lib/models/user.dart', content: FREEZED }]);
  });
  it('json_serializable', () => {
    expect(gen('json_serializable')).toEqual([{ path: 'lib/models/user.dart', content: JSON_SERIALIZABLE }]);
  });
  it('plain', () => {
    expect(gen('plain')).toEqual([{ path: 'lib/models/user.dart', content: PLAIN }]);
  });
});

describe('generateModels', () => {
  it('documents a top-level list response and how to decode it', () => {
    const [f] = gen('plain', ['[{"id":1}]'], 'Post', null);
    expect(f.path).toBe('lib/models/post.dart');
    expect(f.content.split('\n').slice(0, 4)).toEqual([
      '// Generated by Flutter Intercept from 1 recorded response.',
      '// The response is a List<Post>; decode it with:',
      '//   (jsonDecode(body) as List<dynamic>).map((e) => Post.fromJson(e as Map<String, dynamic>)).toList()',
      '',
    ]);
  });

  it('keeps one file per root with every nested class in it, root first', () => {
    const [f] = gen('json_serializable', ['{"a":{"b":{"c":1}},"items":[{"x":1}]}'], 'Order');
    expect([...f.content.matchAll(/^class (\w+)/gm)].map((m) => m[1])).toEqual(['Order', 'A', 'B', 'Item']);
    expect(f.content.match(/^part /gm)).toHaveLength(1);
  });

  it('escapes keys in Dart string literals', () => {
    const [f] = gen('json_serializable', ['{"$ref":"x","it\'s":1}'], 'Doc');
    expect(f.content).toContain("@JsonKey(name: '\\$ref')\n  final String ref;");
    expect(f.content).toContain("@JsonKey(name: 'it\\'s')\n  final int itS;");
    const [p] = gen('plain', ['{"$ref":"x"}'], 'Doc');
    expect(p.content).toContain("ref: json['\\$ref'] as String");
    expect(p.content).toContain("{'\\$ref': ref}");
  });

  it('freezed: renamed keys get @JsonKey on the parameter and the file ignores invalid_annotation_target', () => {
    const [f] = gen('freezed', ['{"first_name":"a"}'], 'P');
    expect(f.content).toContain('// ignore_for_file: invalid_annotation_target');
    expect(f.content).toContain("const factory P({@JsonKey(name: 'first_name') required String firstName}) =\n      _P;");
    const [g] = gen('freezed', ['{"name":"a"}'], 'P');
    expect(g.content).not.toContain('ignore_for_file');
    expect(g.content).toContain('const factory P({required String name}) = _P;');
    expect(g.content).not.toContain('explicitToJson');
  });

  it('handles empty objects in every style', () => {
    expect(gen('freezed', ['{}'], 'E')[0].content).toContain('const factory E() = _E;');
    expect(gen('json_serializable', ['{}'], 'E')[0].content).toContain('  const E();\n');
    const plain = gen('plain', ['{}'], 'E')[0].content;
    expect(plain).toContain('factory E.fromJson(Map<String, dynamic> json) => const E();');
    expect(plain).toContain('Map<String, dynamic> toJson() => {};');
  });

  it('splits long plain fromJson entries like dart format', () => {
    const [f] = gen('plain', ['{"shipping_addresses":[{"street":"s"}],"billing_address":null}', '{"shipping_addresses":[],"billing_address":{"street":"x"}}'], 'Checkout');
    expect(f.content).toContain(
      [
        "    shippingAddresses: (json['shipping_addresses'] as List<dynamic>)",
        '        .map((e) => ShippingAddress.fromJson(e as Map<String, dynamic>))',
        '        .toList(),',
        "    billingAddress: json['billing_address'] == null",
        '        ? null',
        "        : BillingAddress.fromJson(json['billing_address'] as Map<String, dynamic>),",
      ].join('\n'),
    );
  });

  it('source with newlines stays a comment', () => {
    const [f] = gen('plain', ['{}'], 'E', 'GET /a\n/b');
    expect(f.content.startsWith('// Generated by Flutter Intercept from 1 recorded response\n// of GET /a /b.\n')).toBe(true);
  });
});

describe('plain decode / encode expressions', () => {
  const t = {
    int: { kind: 'int', nullable: false },
    intQ: { kind: 'int', nullable: true },
    dbl: { kind: 'double', nullable: false },
    dblQ: { kind: 'double', nullable: true },
    dyn: { kind: 'dynamic' },
    cls: { kind: 'class', name: 'A', nullable: false },
    clsQ: { kind: 'class', name: 'A', nullable: true },
  } as const;

  it('casts primitives and converts num → double', () => {
    expect(decode(t.int, "json['a']", 0)).toBe("json['a'] as int");
    expect(decode(t.intQ, "json['a']", 0)).toBe("json['a'] as int?");
    expect(decode(t.dbl, 'x', 0)).toBe('(x as num).toDouble()');
    expect(decode(t.dblQ, 'x', 0)).toBe('(x as num?)?.toDouble()');
    expect(decode(t.dyn, 'x', 0)).toBe('x');
  });

  it('maps lists and maps, with fresh lambda names per depth', () => {
    expect(decode({ kind: 'list', of: t.dyn, nullable: false }, 'x', 0)).toBe('x as List<dynamic>');
    expect(decode({ kind: 'list', of: t.dyn, nullable: true }, 'x', 0)).toBe('x as List<dynamic>?');
    expect(decode({ kind: 'list', of: { kind: 'list', of: t.dblQ, nullable: false }, nullable: true }, 'x', 0)).toBe(
      '(x as List<dynamic>?)?.map((e) => (e as List<dynamic>).map((e1) => (e1 as num?)?.toDouble()).toList()).toList()',
    );
    expect(decode({ kind: 'map', of: t.clsQ, nullable: false }, 'x', 0)).toBe(
      '(x as Map<String, dynamic>).map((k, e) => MapEntry(k, e == null ? null : A.fromJson(e as Map<String, dynamic>)))',
    );
    expect(decode({ kind: 'map', of: t.int, nullable: false }, 'x', 0)).toBe('(x as Map<String, dynamic>).map((k, e) => MapEntry(k, e as int))');
  });

  it('encodes nested models with toJson, null-aware when nullable', () => {
    expect(encode(t.int, 'a', 0)).toBe('a');
    expect(encode(t.cls, 'a', 0)).toBe('a.toJson()');
    expect(encode(t.clsQ, 'a', 0)).toBe('a?.toJson()');
    expect(encode({ kind: 'list', of: t.clsQ, nullable: true }, 'a', 0)).toBe('a?.map((e) => e?.toJson()).toList()');
    expect(encode({ kind: 'list', of: t.int, nullable: false }, 'a', 0)).toBe('a');
    expect(encode({ kind: 'map', of: t.cls, nullable: false }, 'a', 0)).toBe('a.map((k, e) => MapEntry(k, e.toJson()))');
  });
});
