/**
 * Pure entry-point generator (CONTRACTS §1). No `vscode` import: unit-tested with vitest.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

export const ENTRY_DIR_SEGMENTS = ['.dart_tool', 'flutter_intercept'] as const;

/**
 * CONTRACTS §1 template v3, verbatim. Placeholders: TARGET_IMPORT, PROXY_PORT (default for plain-Dart
 * sessions; Flutter sessions pass `--dart-define=FLUTTER_INTERCEPT_PROXY=<host:port>`), CA_CERT_PEM
 * (this install's CA certificate, trusted by the app; never the key).
 */
export const ENTRY_TEMPLATE = `// GENERATED by Flutter Intercept. Do not edit. Safe to delete.
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import '{{TARGET_IMPORT}}' as target; // package:<app>/<path> when under lib/, else relative

// Flutter sessions pass --dart-define=FLUTTER_INTERCEPT_PROXY=<host:port> (device dependent);
// the default serves plain Dart sessions, which run on the host and take no dart-define.
const _proxyAddress = String.fromEnvironment('FLUTTER_INTERCEPT_PROXY', defaultValue: 'localhost:{{PROXY_PORT}}');
const _proxy = 'PROXY $_proxyAddress; DIRECT';

String _findProxy(Uri url) => _proxy;

// Certificate of this machine's Flutter Intercept CA (its private key never leaves the
// development machine). It is *trusted* in addition to the normal roots, so the proxy's
// per-host certificates pass ordinary chain + hostname verification, and DIRECT traffic
// (proxy unreachable) is verified exactly as without Flutter Intercept.
const _caCertificate = r'''
{{CA_CERT_PEM}}''';

final Expando<bool> _trustedContexts = Expando<bool>();
void _trustCa(SecurityContext context) {
  if (_trustedContexts[context] == true) return;
  _trustedContexts[context] = true;
  try {
    context.setTrustedCertificatesBytes(utf8.encode(_caCertificate));
  } catch (e) {
    // Already present (e.g. CERT_ALREADY_IN_HASH_TABLE) is fine. Otherwise interception of
    // this context's HTTPS fails closed: the TLS handshake fails and Dart falls back to DIRECT.
    if (!'$e'.contains('ALREADY')) _note('could not trust the Flutter Intercept CA: $e');
  }
}

final Set<String> _noted = <String>{};
void _note(String message) {
  if (_noted.add(message)) print('[flutter_intercept] $message');
}

class _FlutterInterceptOverrides extends HttpOverrides {
  _FlutterInterceptOverrides(this._previous);
  final HttpOverrides? _previous;
  bool _creating = false;

  @override
  HttpClient createHttpClient(SecurityContext? context) {
    // Re-entered from a delegate that calls HttpClient() itself: give it a
    // plain client; the outer call configures and wraps it.
    if (_creating) return super.createHttpClient(context);
    _trustCa(context ?? SecurityContext.defaultContext);
    // Our zone value shadows any HttpOverrides.global the app installs later;
    // delegate to it so the app's own overrides still apply underneath ours.
    final global = Zone.root.run(() => HttpOverrides.current);
    final delegate = (global != null && !identical(global, this)) ? global : _previous;
    HttpClient client;
    if (delegate != null) {
      _creating = true;
      try {
        client = delegate.createHttpClient(context);
      } finally {
        _creating = false;
      }
    } else {
      client = super.createHttpClient(context);
    }
    if (client is _InterceptedHttpClient) return client;
    client.findProxy = _findProxy;
    return _InterceptedHttpClient(client);
  }
}

/// Forwards every member to the real client, except that app assignments to
/// \`findProxy\` made after creation (Charles-style snippets,
/// findProxyFromEnvironment) are ignored so traffic stays on the proxy.
/// \`badCertificateCallback\` is the app's own (forwarded): it is never consulted
/// for proxy certificates, which are trusted, and keeps its meaning on DIRECT.
/// Callback setters take \`dynamic\` so their exact function types can never
/// mismatch the SDK; members added by future SDKs reach \`noSuchMethod\`.
class _InterceptedHttpClient implements HttpClient {
  _InterceptedHttpClient(this._client);
  final HttpClient _client;

  @override
  set findProxy(dynamic f) {
    if (f != null) _note('ignored app findProxy (requests stay on the intercept proxy)');
  }

  @override
  set badCertificateCallback(dynamic callback) => _client.badCertificateCallback = callback;

  @override
  set connectionFactory(dynamic f) {
    if (f != null) _note('app set connectionFactory: its connections may bypass the intercept proxy');
    _client.connectionFactory = f;
  }

  @override
  Duration get idleTimeout => _client.idleTimeout;
  @override
  set idleTimeout(Duration value) => _client.idleTimeout = value;
  @override
  Duration? get connectionTimeout => _client.connectionTimeout;
  @override
  set connectionTimeout(Duration? value) => _client.connectionTimeout = value;
  @override
  int? get maxConnectionsPerHost => _client.maxConnectionsPerHost;
  @override
  set maxConnectionsPerHost(int? value) => _client.maxConnectionsPerHost = value;
  @override
  bool get autoUncompress => _client.autoUncompress;
  @override
  set autoUncompress(bool value) => _client.autoUncompress = value;
  @override
  String? get userAgent => _client.userAgent;
  @override
  set userAgent(String? value) => _client.userAgent = value;

  @override
  Future<HttpClientRequest> open(String method, String host, int port, String path) =>
      _client.open(method, host, port, path);
  @override
  Future<HttpClientRequest> openUrl(String method, Uri url) => _client.openUrl(method, url);
  @override
  Future<HttpClientRequest> get(String host, int port, String path) => _client.get(host, port, path);
  @override
  Future<HttpClientRequest> getUrl(Uri url) => _client.getUrl(url);
  @override
  Future<HttpClientRequest> post(String host, int port, String path) => _client.post(host, port, path);
  @override
  Future<HttpClientRequest> postUrl(Uri url) => _client.postUrl(url);
  @override
  Future<HttpClientRequest> put(String host, int port, String path) => _client.put(host, port, path);
  @override
  Future<HttpClientRequest> putUrl(Uri url) => _client.putUrl(url);
  @override
  Future<HttpClientRequest> delete(String host, int port, String path) =>
      _client.delete(host, port, path);
  @override
  Future<HttpClientRequest> deleteUrl(Uri url) => _client.deleteUrl(url);
  @override
  Future<HttpClientRequest> patch(String host, int port, String path) =>
      _client.patch(host, port, path);
  @override
  Future<HttpClientRequest> patchUrl(Uri url) => _client.patchUrl(url);
  @override
  Future<HttpClientRequest> head(String host, int port, String path) => _client.head(host, port, path);
  @override
  Future<HttpClientRequest> headUrl(Uri url) => _client.headUrl(url);

  @override
  set authenticate(dynamic f) => _client.authenticate = f;
  @override
  void addCredentials(Uri url, String realm, HttpClientCredentials credentials) =>
      _client.addCredentials(url, realm, credentials);
  @override
  set authenticateProxy(dynamic f) => _client.authenticateProxy = f;
  @override
  void addProxyCredentials(String host, int port, String realm, HttpClientCredentials credentials) =>
      _client.addProxyCredentials(host, port, realm, credentials);
  @override
  set keyLog(dynamic callback) => _client.keyLog = callback;
  @override
  void close({bool force = false}) => _client.close(force: force);

  // Only reached for HttpClient members added by a future SDK (all members of
  // Dart 3.0-3.13 are forwarded above). Setters are dropped (the app keeps
  // working with the SDK default); getters/methods cannot be forwarded.
  @override
  dynamic noSuchMethod(Invocation invocation) {
    _note('HttpClient member \${invocation.memberName} is not supported by this Flutter Intercept version'
        '\${invocation.isSetter ? ' (assignment ignored)' : ''}');
    if (invocation.isSetter) return null;
    return super.noSuchMethod(invocation);
  }
}

Future<void> main(List<String> args) async {
  _trustCa(SecurityContext.defaultContext);
  final overrides = _FlutterInterceptOverrides(HttpOverrides.current);
  HttpOverrides.global = overrides;
  // Zone value wins over a later \`HttpOverrides.global = ...\` inside the app.
  await HttpOverrides.runWithHttpOverrides(() async {
    // Works for \`void main()\`, \`Future<void> main() async\` and \`main(List<String>)\`.
    final dynamic entry = target.main;
    final dynamic result = entry is Function(List<String>) ? entry(args) : entry();
    if (result is Future) await result;
  }, overrides);
}
`;

export interface FsLike {
  existsSync(p: string): boolean;
  readFileSync(p: string, enc: 'utf8'): string;
  statSync(p: string): { isDirectory(): boolean; isFile(): boolean };
}

const realFs: FsLike = fs;

export function hasPubspec(dir: string, f: FsLike = realFs): boolean {
  return f.existsSync(path.join(dir, 'pubspec.yaml'));
}

/** Nearest directory at or above `start` (a file or directory) containing pubspec.yaml. */
export function findPubspecRoot(start: string, f: FsLike = realFs): string | undefined {
  let dir = start;
  try {
    if (!f.statSync(start).isDirectory()) dir = path.dirname(start);
  } catch {
    dir = path.dirname(start);
  }
  for (;;) {
    if (hasPubspec(dir, f)) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

export interface PubspecInfo {
  name?: string;
  /** true when dependencies/dev_dependencies reference flutter, flutter_test or sky_engine (same rule as Dart-Code). */
  isFlutter: boolean;
}

/** Minimal pubspec reader: top-level `name:` and whether Flutter is a (dev_)dependency. */
export function parsePubspec(content: string): PubspecInfo {
  let name: string | undefined;
  let isFlutter = false;
  let section: string | undefined;
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.replace(/\s+#.*$/, '').replace(/^#.*$/, '');
    if (!line.trim()) continue;
    const top = /^([A-Za-z_][\w-]*)\s*:\s*(.*)$/.exec(line);
    if (top) {
      section = top[1];
      if (section === 'name') {
        const v = top[2].trim().replace(/^['"]|['"]$/g, '');
        if (v) name = v;
      }
      continue;
    }
    if (section === 'dependencies' || section === 'dev_dependencies') {
      const dep = /^\s+([A-Za-z_][\w]*)\s*:/.exec(line);
      if (dep && /^(flutter|flutter_test|sky_engine)$/.test(dep[1])) isFlutter = true;
    }
  }
  return { name, isFlutter };
}

export function readPubspec(root: string, f: FsLike = realFs): PubspecInfo {
  try {
    return parsePubspec(f.readFileSync(path.join(root, 'pubspec.yaml'), 'utf8'));
  } catch {
    return { isFlutter: false };
  }
}

/** True when `child` is `parent` or inside it. */
export function isWithin(child: string, parent: string): boolean {
  const rel = path.relative(parent, child);
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

function toPosix(p: string): string {
  return p.split(path.sep).join('/');
}

function encodeUriPath(p: string): string {
  return p
    .split('/')
    .map((seg) => (seg === '..' || seg === '.' ? seg : encodeURIComponent(seg)))
    .join('/');
}

/**
 * CONTRACTS §1 naming: the target's full project-relative path without `.dart`, `/` → `__`
 * (`lib/main.dart` → `entry_lib__main.dart`, `lib/flavors/dev/main.dart` →
 * `entry_lib__flavors__dev__main.dart`), so two targets never share an entry. When that mapping is
 * lossy (a character outside `[A-Za-z0-9_]` replaced, or `__` already in a segment) or the target is
 * outside the project root, `_<first 8 hex of sha1(path)>` is appended to keep names unique.
 */
export function entryNameFor(projectRoot: string, program: string): string {
  const inside = isWithin(program, projectRoot);
  const rel = inside ? toPosix(path.relative(projectRoot, program)) : path.basename(program);
  const segs = rel.replace(/\.dart$/i, '').split('/');
  const clean = segs.map((seg) => seg.replace(/[^A-Za-z0-9_]/g, '_'));
  const lossy = !inside || segs.some((seg, i) => seg !== clean[i] || seg.includes('__'));
  const suffix = lossy
    ? '_' + crypto.createHash('sha1').update(inside ? rel : toPosix(path.resolve(program))).digest('hex').slice(0, 8)
    : '';
  return `entry_${clean.join('__')}${suffix}.dart`;
}

export function entryPathFor(projectRoot: string, program: string): string {
  return path.join(projectRoot, ...ENTRY_DIR_SEGMENTS, entryNameFor(projectRoot, program));
}

/** True when `program` is a file generated by us (any project). */
export function isGeneratedEntry(program: string | undefined): boolean {
  if (!program) return false;
  const p = program.replace(/\\/g, '/');
  return /\/\.dart_tool\/flutter_intercept\/entry_[^/]*\.dart$/.test(p);
}

/**
 * Import URI for `program` as seen from the generated entry file.
 * `package:<name>/<path-under-lib>` when the program is under `<root>/lib/` and the package
 * has a name (avoids loading the same library twice under two URIs), else a relative URI.
 */
export function targetImportFor(projectRoot: string, packageName: string | undefined, program: string, entryFile: string): string {
  const lib = path.join(projectRoot, 'lib');
  if (packageName && isWithin(program, lib) && program !== lib) {
    return `package:${packageName}/${encodeUriPath(toPosix(path.relative(lib, program)))}`;
  }
  const rel = path.relative(path.dirname(entryFile), program);
  if (path.isAbsolute(rel) || /^[A-Za-z]:/.test(rel)) {
    // Different drive on Windows: fall back to an absolute file URI.
    return 'file:///' + encodeUriPath(toPosix(program).replace(/^\//, ''));
  }
  return encodeUriPath(toPosix(rel));
}

export interface RenderOptions {
  targetImport: string;
  /** Default proxy port baked into the entry (plain-Dart sessions); Flutter sessions use the dart-define. */
  proxyPort: number;
  /** PEM certificate of this install's CA (never the private key). */
  caCertPem: string;
}

/** `--dart-define` name carrying `<host>:<port>` for Flutter sessions (CONTRACTS §1/§2). */
export const PROXY_DEFINE = 'FLUTTER_INTERCEPT_PROXY';

/** Exactly one PEM certificate block, nothing else (it is embedded in a Dart raw string). */
export function normalizeCaCertPem(pem: string): string {
  const blocks = pem.match(/-----BEGIN CERTIFICATE-----[A-Za-z0-9+/=\s]+?-----END CERTIFICATE-----/g) ?? [];
  if (blocks.length !== 1) throw new Error(`expected exactly one PEM certificate, got ${blocks.length}`);
  return blocks[0].replace(/\r\n?/g, '\n').trim();
}

/**
 * Renders the entry. An empty `caCertPem` leaves the CA placeholder in place: such a plan is only
 * used to decide whether a launch is intercepted, and `writeEntry` refuses to write it.
 */
export function renderEntry(opts: RenderOptions): string {
  const out = ENTRY_TEMPLATE
    .replace('{{TARGET_IMPORT}}', opts.targetImport.replace(/'/g, "\\'"))
    .replace('{{PROXY_PORT}}', String(opts.proxyPort));
  if (!opts.caCertPem) return out;
  const ca = normalizeCaCertPem(opts.caCertPem);
  return out.replace('{{CA_CERT_PEM}}', () => ca + '\n');
}

/** First 12 hex chars of sha1(entry bytes), for `--dart-define=FLUTTER_INTERCEPT_ENTRY_SHA=` (CONTRACTS §1). */
export function entrySha(content: string): string {
  return crypto.createHash('sha1').update(Buffer.from(content, 'utf8')).digest('hex').slice(0, 12);
}

export interface EntryPlanInput {
  /** Absolute path of the app's real entry point (already resolved). */
  program: string;
  /** Fallback root when no pubspec.yaml is found above the program (cwd or workspace folder). */
  fallbackRoot?: string;
  proxyPort: number;
  caCertPem: string;
}

export interface EntryPlan {
  projectRoot: string;
  packageName?: string;
  isFlutter: boolean;
  program: string;
  entryPath: string;
  targetImport: string;
  content: string;
  /** entrySha(content) */
  sha: string;
}

export function planEntry(input: EntryPlanInput, f: FsLike = realFs): EntryPlan | undefined {
  const program = path.resolve(input.program);
  const projectRoot = findPubspecRoot(program, f) ?? input.fallbackRoot;
  if (!projectRoot) return undefined;
  const pubspec = readPubspec(projectRoot, f);
  const entryPath = entryPathFor(projectRoot, program);
  const targetImport = targetImportFor(projectRoot, pubspec.name, program, entryPath);
  const content = renderEntry({ targetImport, proxyPort: input.proxyPort, caCertPem: input.caCertPem });
  return { projectRoot, packageName: pubspec.name, isFlutter: pubspec.isFlutter, program, entryPath, targetImport, content, sha: entrySha(content) };
}

/** Writes the planned entry (creating the directory). Only rewrites when content changed. */
export async function writeEntry(plan: EntryPlan): Promise<void> {
  if (plan.content.includes('{{CA_CERT_PEM}}')) throw new Error('refusing to write an entry without the CA certificate');
  await fs.promises.mkdir(path.dirname(plan.entryPath), { recursive: true });
  try {
    const existing = await fs.promises.readFile(plan.entryPath, 'utf8');
    if (existing === plan.content) return;
  } catch {
    // does not exist yet
  }
  await fs.promises.writeFile(plan.entryPath, plan.content, 'utf8');
}
