/**
 * Pure entry-point generator (CONTRACTS §1). No `vscode` import: unit-tested with vitest.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

export const ENTRY_DIR_SEGMENTS = ['.dart_tool', 'flutter_intercept'] as const;

/**
 * Template v4 = CONTRACTS §1 (v3) + §9.1 request → source, verbatim (source of truth:
 * scripts/e2e/templates/entry_v4.dart.tmpl, docs/spikes/template-v4.md). Placeholders: TARGET_IMPORT,
 * PROXY_PORT (default for plain-Dart sessions; Flutter sessions pass
 * `--dart-define=FLUTTER_INTERCEPT_PROXY=<host:port>`), CA_CERT_PEM (this install's CA certificate,
 * trusted by the app; never the key). `--dart-define=FLUTTER_INTERCEPT_TRACE=0` turns tracing off.
 */
export const ENTRY_TEMPLATE = `// GENERATED by Flutter Intercept. Do not edit. Safe to delete.
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import '{{TARGET_IMPORT}}' as target; // package:<app>/<path> when under lib/, else relative

// Flutter sessions pass --dart-define=FLUTTER_INTERCEPT_PROXY=<host:port> (device dependent);
// the default serves plain Dart sessions, which run on the host and take no dart-define.
const _proxyAddress = String.fromEnvironment('FLUTTER_INTERCEPT_PROXY', defaultValue: 'localhost:{{PROXY_PORT}}');
const _proxy = 'PROXY $_proxyAddress; DIRECT';

String _findProxy(Uri url) => _proxy;

// Request -> source (CONTRACTS §9.1). Each request carries an opaque \`x-fi-id\` header; the stack
// captured when the app opened it goes to the proxy out of band (never upstream). Flutter sessions
// pass --dart-define=FLUTTER_INTERCEPT_TRACE=0 when the user turned it off.
const _traceEnabled = String.fromEnvironment('FLUTTER_INTERCEPT_TRACE') != '0';
// Libraries such as Dio open the connection several async hops after the app's call, so the stack at
// that point no longer shows it. In debug (JIT) sessions the app runs in a zone that remembers where
// each callback was registered (like package:stack_trace's Chain.capture); never in profile builds.
const _traceChains = _traceEnabled && !bool.fromEnvironment('dart.vm.profile') && !bool.fromEnvironment('dart.vm.product');
const _traceHeader = 'x-fi-id';
// \`.invalid\` never resolves and the side channel has no \`; DIRECT\`: stacks only ever reach the proxy.
final Uri _traceUrl = Uri.parse('https://trace.flutter-intercept.invalid/v1/traces');
const _traceMaxChars = 16000;
const _traceBatch = 50;
const _traceQueueLimit = 1000;
// Flutter apps keep the side channel's connection for the next batch; plain Dart programs close it.
const _flutterApp = bool.fromEnvironment('dart.library.ui');

// Random per isolate start (so ids stay unique across hot restarts) + a counter.
final String _tracePrefix = () {
  Random random;
  try {
    random = Random.secure();
  } catch (_) {
    random = Random(DateTime.now().microsecondsSinceEpoch);
  }
  final buffer = StringBuffer();
  for (var i = 0; i < 16; i++) {
    buffer.write(random.nextInt(16).toRadixString(16));
  }
  return buffer.toString();
}();
int _traceCount = 0;

class _PendingTrace {
  _PendingTrace(this.id, this.stack, this.chain);
  final String id;
  final StackTrace stack;
  final List<StackTrace>? chain;

  /// The VM stack, then (whole) earlier registrations in package:stack_trace's Chain format.
  String format() {
    var out = _lean('$stack');
    final c = chain;
    if (c != null) {
      for (final t in c) {
        final segment = _lean('$t');
        if (segment.isEmpty) continue;
        final next = '$out$_chainGap\\n$segment';
        if (next.length > _traceMaxChars) break;
        out = next;
      }
    }
    return out.length > _traceMaxChars ? out.substring(0, _traceMaxChars) : out;
  }
}

/// VM stack lines without frames of \`dart:\` libraries and of this file (event loop and zone
/// plumbing, never the app's call site); \`<asynchronous suspension>\` markers between kept frames stay.
String _lean(String trace) {
  final out = StringBuffer();
  var suspended = false;
  for (final line in trace.split('\\n')) {
    if (line.isEmpty) continue;
    if (line == '<asynchronous suspension>') {
      suspended = true;
      continue;
    }
    if (line.contains('(dart:') || (line.contains('/.dart_tool/') && line.contains('/entry_'))) continue;
    if (suspended && out.isNotEmpty) out.write('<asynchronous suspension>\\n');
    suspended = false;
    out.write('$line\\n');
  }
  return out.toString();
}

const _chainDepth = 10;
const _chainGap = '===== asynchronous gap ===========================';
// Registration stacks of the callback running now, newest first (null outside the chain zone).
List<StackTrace>? _currentChain;

List<StackTrace> _chainHere() {
  final parent = _currentChain;
  final out = <StackTrace>[StackTrace.current];
  if (parent != null) {
    for (var i = 0; i < parent.length && out.length < _chainDepth; i++) {
      out.add(parent[i]);
    }
  }
  return out;
}

// Microtasks and timers keep the chain they were scheduled under without a capture of their own: they
// are scheduled at least once per \`await\`, which would double the cost, and the code that schedules
// one from the app's call already registered a \`then\` (captured below) or runs the app's own closure.
ZoneCallback<R> _registerCallback<R>(Zone self, ZoneDelegate parent, Zone zone, R Function() f) {
  final chain = _currentChain;
  final g = parent.registerCallback<R>(zone, f);
  if (chain == null) return g;
  return () {
    final previous = _currentChain;
    _currentChain = chain;
    try {
      return g();
    } finally {
      _currentChain = previous;
    }
  };
}

ZoneUnaryCallback<R, T> _registerUnaryCallback<R, T>(Zone self, ZoneDelegate parent, Zone zone, R Function(T) f) {
  final chain = _chainHere();
  final g = parent.registerUnaryCallback<R, T>(zone, f);
  return (T a) {
    final previous = _currentChain;
    _currentChain = chain;
    try {
      return g(a);
    } finally {
      _currentChain = previous;
    }
  };
}

// Error handlers keep the chain they were registered under without a capture of their own (half the
// cost of an \`await\`); a retry from an error handler still leads back to the app's call.
ZoneBinaryCallback<R, T1, T2> _registerBinaryCallback<R, T1, T2>(
    Zone self, ZoneDelegate parent, Zone zone, R Function(T1, T2) f) {
  final chain = _currentChain;
  final g = parent.registerBinaryCallback<R, T1, T2>(zone, f);
  if (chain == null) return g;
  return (T1 a, T2 b) {
    final previous = _currentChain;
    _currentChain = chain;
    try {
      return g(a, b);
    } finally {
      _currentChain = previous;
    }
  };
}

final List<_PendingTrace> _pendingTraces = <_PendingTrace>[];
Timer? _traceTimer;
int _tracePosts = 0;
HttpClient? _traceClient;
bool _traceFailed = false;

/// Tags a request the app is opening with an id and queues the app's stack for the proxy.
/// Must be called synchronously from the HttpClient member the app called.
Future<HttpClientRequest> _traced(Future<HttpClientRequest> request) {
  if (!_traceEnabled) return request;
  final stack = StackTrace.current;
  _traceCount++;
  final id = '$_tracePrefix-\${_traceCount.toRadixString(36)}';
  if (_pendingTraces.length >= _traceQueueLimit) _pendingTraces.removeAt(0);
  _pendingTraces.add(_PendingTrace(id, stack, _currentChain));
  _traceTimer ??= Zone.root.createTimer(const Duration(milliseconds: 100), _flushTraces);
  return request.then((HttpClientRequest r) {
    try {
      r.headers.set(_traceHeader, id);
    } catch (_) {
      // Headers already sent or immutable: this request just has no source.
    }
    return r;
  });
}

void _flushTraces() {
  _traceTimer = null;
  while (_pendingTraces.isNotEmpty) {
    final n = _pendingTraces.length < _traceBatch ? _pendingTraces.length : _traceBatch;
    final batch = _pendingTraces.sublist(0, n);
    _pendingTraces.removeRange(0, n);
    _postTraces(batch);
  }
}

class _UntracedOverrides extends HttpOverrides {}

Future<void> _postTraces(List<_PendingTrace> batch) async {
  _tracePosts++;
  try {
    // A plain dart:io client (not the app's, not wrapped, never traced) that may only use the proxy, over
    // one connection so batches never compete with the app for the proxy's per-client connection budget.
    final client = _traceClient ??=
        HttpOverrides.runWithHttpOverrides<HttpClient>(() => HttpClient(), _UntracedOverrides())
          ..findProxy = ((Uri url) => 'PROXY $_proxyAddress')
          ..maxConnectionsPerHost = 1;
    final traces = <Map<String, String>>[];
    for (final t in batch) {
      traces.add(<String, String>{'id': t.id, 'stack': t.format()});
    }
    final body = utf8.encode(jsonEncode(<String, Object>{'traces': traces}));
    final request = await client.postUrl(_traceUrl);
    request.headers.contentType = ContentType.json;
    request.contentLength = body.length;
    request.add(body);
    final response = await request.close();
    await response.drain<void>();
  } catch (e) {
    if (!_traceFailed) {
      _traceFailed = true;
      _note('request sources are unavailable (could not reach the intercept proxy: $e)');
    }
  } finally {
    _tracePosts--;
    // An idle keep-alive connection would hold a plain Dart program open for 15 s.
    if (!_flutterApp && _tracePosts == 0 && _pendingTraces.isEmpty && _traceTimer == null) {
      _traceClient?.close();
      _traceClient = null;
    }
  }
}

// Certificate of this machine's Flutter Intercept CA (its private key never leaves the
// development machine). It is *trusted* in addition to the normal roots, so the proxy's
// per-host certificates pass ordinary chain + hostname verification, and DIRECT traffic
// (proxy unreachable) is verified exactly as without Flutter Intercept.
const _caCertificate = r'''
{{CA_CERT_PEM}}''';

final Expando<bool> _trustedContexts = Expando<bool>();
void _trustCa(SecurityContext context) {
  if (_trustedContexts[context] == true) return;
  _trustedContexts[context] = true;
  try {
    context.setTrustedCertificatesBytes(utf8.encode(_caCertificate));
  } catch (e) {
    // Already present (e.g. CERT_ALREADY_IN_HASH_TABLE) is fine. Otherwise interception of
    // this context's HTTPS fails closed: the TLS handshake fails and Dart falls back to DIRECT.
    if (!'$e'.contains('ALREADY')) _note('could not trust the Flutter Intercept CA: $e');
  }
}

final Set<String> _noted = <String>{};
void _note(String message) {
  if (_noted.add(message)) print('[flutter_intercept] $message');
}

class _FlutterInterceptOverrides extends HttpOverrides {
  _FlutterInterceptOverrides(this._previous);
  final HttpOverrides? _previous;
  bool _creating = false;

  @override
  HttpClient createHttpClient(SecurityContext? context) {
    // Re-entered from a delegate that calls HttpClient() itself: give it a
    // plain client; the outer call configures and wraps it.
    if (_creating) return super.createHttpClient(context);
    _trustCa(context ?? SecurityContext.defaultContext);
    // Our zone value shadows any HttpOverrides.global the app installs later;
    // delegate to it so the app's own overrides still apply underneath ours.
    final global = Zone.root.run(() => HttpOverrides.current);
    final delegate = (global != null && !identical(global, this)) ? global : _previous;
    HttpClient client;
    if (delegate != null) {
      _creating = true;
      try {
        client = delegate.createHttpClient(context);
      } finally {
        _creating = false;
      }
    } else {
      client = super.createHttpClient(context);
    }
    if (client is _InterceptedHttpClient) return client;
    client.findProxy = _findProxy;
    return _InterceptedHttpClient(client);
  }
}

/// Forwards every member to the real client, except that app assignments to
/// \`findProxy\` made after creation (Charles-style snippets,
/// findProxyFromEnvironment) are ignored so traffic stays on the proxy.
/// \`badCertificateCallback\` is the app's own (forwarded): it is never consulted
/// for proxy certificates, which are trusted, and keeps its meaning on DIRECT.
/// Callback setters take \`dynamic\` so their exact function types can never
/// mismatch the SDK; members added by future SDKs reach \`noSuchMethod\`.
class _InterceptedHttpClient implements HttpClient {
  _InterceptedHttpClient(this._client);
  final HttpClient _client;

  @override
  set findProxy(dynamic f) {
    if (f != null) _note('ignored app findProxy (requests stay on the intercept proxy)');
  }

  @override
  set badCertificateCallback(dynamic callback) => _client.badCertificateCallback = callback;

  @override
  set connectionFactory(dynamic f) {
    if (f != null) _note('app set connectionFactory: its connections may bypass the intercept proxy');
    _client.connectionFactory = f;
  }

  @override
  Duration get idleTimeout => _client.idleTimeout;
  @override
  set idleTimeout(Duration value) => _client.idleTimeout = value;
  @override
  Duration? get connectionTimeout => _client.connectionTimeout;
  @override
  set connectionTimeout(Duration? value) => _client.connectionTimeout = value;
  @override
  int? get maxConnectionsPerHost => _client.maxConnectionsPerHost;
  @override
  set maxConnectionsPerHost(int? value) => _client.maxConnectionsPerHost = value;
  @override
  bool get autoUncompress => _client.autoUncompress;
  @override
  set autoUncompress(bool value) => _client.autoUncompress = value;
  @override
  String? get userAgent => _client.userAgent;
  @override
  set userAgent(String? value) => _client.userAgent = value;

  @override
  Future<HttpClientRequest> open(String method, String host, int port, String path) =>
      _traced(_client.open(method, host, port, path));
  @override
  Future<HttpClientRequest> openUrl(String method, Uri url) => _traced(_client.openUrl(method, url));
  @override
  Future<HttpClientRequest> get(String host, int port, String path) => _traced(_client.get(host, port, path));
  @override
  Future<HttpClientRequest> getUrl(Uri url) => _traced(_client.getUrl(url));
  @override
  Future<HttpClientRequest> post(String host, int port, String path) => _traced(_client.post(host, port, path));
  @override
  Future<HttpClientRequest> postUrl(Uri url) => _traced(_client.postUrl(url));
  @override
  Future<HttpClientRequest> put(String host, int port, String path) => _traced(_client.put(host, port, path));
  @override
  Future<HttpClientRequest> putUrl(Uri url) => _traced(_client.putUrl(url));
  @override
  Future<HttpClientRequest> delete(String host, int port, String path) =>
      _traced(_client.delete(host, port, path));
  @override
  Future<HttpClientRequest> deleteUrl(Uri url) => _traced(_client.deleteUrl(url));
  @override
  Future<HttpClientRequest> patch(String host, int port, String path) =>
      _traced(_client.patch(host, port, path));
  @override
  Future<HttpClientRequest> patchUrl(Uri url) => _traced(_client.patchUrl(url));
  @override
  Future<HttpClientRequest> head(String host, int port, String path) => _traced(_client.head(host, port, path));
  @override
  Future<HttpClientRequest> headUrl(Uri url) => _traced(_client.headUrl(url));

  @override
  set authenticate(dynamic f) => _client.authenticate = f;
  @override
  void addCredentials(Uri url, String realm, HttpClientCredentials credentials) =>
      _client.addCredentials(url, realm, credentials);
  @override
  set authenticateProxy(dynamic f) => _client.authenticateProxy = f;
  @override
  void addProxyCredentials(String host, int port, String realm, HttpClientCredentials credentials) =>
      _client.addProxyCredentials(host, port, realm, credentials);
  @override
  set keyLog(dynamic callback) => _client.keyLog = callback;
  @override
  void close({bool force = false}) => _client.close(force: force);

  // Only reached for HttpClient members added by a future SDK (all members of
  // Dart 3.0-3.13 are forwarded above). Setters are dropped (the app keeps
  // working with the SDK default); getters/methods cannot be forwarded.
  @override
  dynamic noSuchMethod(Invocation invocation) {
    _note('HttpClient member \${invocation.memberName} is not supported by this Flutter Intercept version'
        '\${invocation.isSetter ? ' (assignment ignored)' : ''}');
    if (invocation.isSetter) return null;
    return super.noSuchMethod(invocation);
  }
}

Future<void> main(List<String> args) async {
  _trustCa(SecurityContext.defaultContext);
  final overrides = _FlutterInterceptOverrides(HttpOverrides.current);
  HttpOverrides.global = overrides;
  // Zone value wins over a later \`HttpOverrides.global = ...\` inside the app.
  await HttpOverrides.runWithHttpOverrides(() {
    if (!_traceChains) return _runTarget(args);
    return runZoned(() => _runTarget(args),
        zoneSpecification: ZoneSpecification(
            registerCallback: _registerCallback,
            registerUnaryCallback: _registerUnaryCallback,
            registerBinaryCallback: _registerBinaryCallback));
  }, overrides);
}

Future<void> _runTarget(List<String> args) async {
  // Works for \`void main()\`, \`Future<void> main() async\` and \`main(List<String>)\`.
  final dynamic entry = target.main;
  final dynamic result = entry is Function(List<String>) ? entry(args) : entry();
  if (result is Future) await result;
}
`;

export interface FsLike {
  existsSync(p: string): boolean;
  readFileSync(p: string, enc: 'utf8'): string;
  statSync(p: string): { isDirectory(): boolean; isFile(): boolean };
}

const realFs: FsLike = fs;

export function hasPubspec(dir: string, f: FsLike = realFs): boolean {
  return f.existsSync(path.join(dir, 'pubspec.yaml'));
}

/** Nearest directory at or above `start` (a file or directory) containing pubspec.yaml. */
export function findPubspecRoot(start: string, f: FsLike = realFs): string | undefined {
  let dir = start;
  try {
    if (!f.statSync(start).isDirectory()) dir = path.dirname(start);
  } catch {
    dir = path.dirname(start);
  }
  for (;;) {
    if (hasPubspec(dir, f)) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

export interface PubspecInfo {
  name?: string;
  /** true when dependencies/dev_dependencies reference flutter, flutter_test or sky_engine (same rule as Dart-Code). */
  isFlutter: boolean;
}

/** Minimal pubspec reader: top-level `name:` and whether Flutter is a (dev_)dependency. */
export function parsePubspec(content: string): PubspecInfo {
  let name: string | undefined;
  let isFlutter = false;
  let section: string | undefined;
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.replace(/\s+#.*$/, '').replace(/^#.*$/, '');
    if (!line.trim()) continue;
    const top = /^([A-Za-z_][\w-]*)\s*:\s*(.*)$/.exec(line);
    if (top) {
      section = top[1];
      if (section === 'name') {
        const v = top[2].trim().replace(/^['"]|['"]$/g, '');
        if (v) name = v;
      }
      continue;
    }
    if (section === 'dependencies' || section === 'dev_dependencies') {
      const dep = /^\s+([A-Za-z_][\w]*)\s*:/.exec(line);
      if (dep && /^(flutter|flutter_test|sky_engine)$/.test(dep[1])) isFlutter = true;
    }
  }
  return { name, isFlutter };
}

export function readPubspec(root: string, f: FsLike = realFs): PubspecInfo {
  try {
    return parsePubspec(f.readFileSync(path.join(root, 'pubspec.yaml'), 'utf8'));
  } catch {
    return { isFlutter: false };
  }
}

/** True when `child` is `parent` or inside it. */
export function isWithin(child: string, parent: string): boolean {
  const rel = path.relative(parent, child);
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

function toPosix(p: string): string {
  return p.split(path.sep).join('/');
}

function encodeUriPath(p: string): string {
  return p
    .split('/')
    .map((seg) => (seg === '..' || seg === '.' ? seg : encodeURIComponent(seg)))
    .join('/');
}

/**
 * CONTRACTS §1 naming: the target's full project-relative path without `.dart`, `/` → `__`
 * (`lib/main.dart` → `entry_lib__main.dart`, `lib/flavors/dev/main.dart` →
 * `entry_lib__flavors__dev__main.dart`), so two targets never share an entry. When that mapping is
 * lossy (a character outside `[A-Za-z0-9_]` replaced, or `__` already in a segment) or the target is
 * outside the project root, `_<first 8 hex of sha1(path)>` is appended to keep names unique.
 */
export function entryNameFor(projectRoot: string, program: string): string {
  const inside = isWithin(program, projectRoot);
  const rel = inside ? toPosix(path.relative(projectRoot, program)) : path.basename(program);
  const segs = rel.replace(/\.dart$/i, '').split('/');
  const clean = segs.map((seg) => seg.replace(/[^A-Za-z0-9_]/g, '_'));
  const lossy = !inside || segs.some((seg, i) => seg !== clean[i] || seg.includes('__'));
  const suffix = lossy
    ? '_' + crypto.createHash('sha1').update(inside ? rel : toPosix(path.resolve(program))).digest('hex').slice(0, 8)
    : '';
  return `entry_${clean.join('__')}${suffix}.dart`;
}

export function entryPathFor(projectRoot: string, program: string): string {
  return path.join(projectRoot, ...ENTRY_DIR_SEGMENTS, entryNameFor(projectRoot, program));
}

/** True when `program` is a file generated by us (any project). */
export function isGeneratedEntry(program: string | undefined): boolean {
  if (!program) return false;
  const p = program.replace(/\\/g, '/');
  return /\/\.dart_tool\/flutter_intercept\/entry_[^/]*\.dart$/.test(p);
}

/**
 * Import URI for `program` as seen from the generated entry file.
 * `package:<name>/<path-under-lib>` when the program is under `<root>/lib/` and the package
 * has a name (avoids loading the same library twice under two URIs), else a relative URI.
 */
export function targetImportFor(projectRoot: string, packageName: string | undefined, program: string, entryFile: string): string {
  const lib = path.join(projectRoot, 'lib');
  if (packageName && isWithin(program, lib) && program !== lib) {
    return `package:${packageName}/${encodeUriPath(toPosix(path.relative(lib, program)))}`;
  }
  const rel = path.relative(path.dirname(entryFile), program);
  if (path.isAbsolute(rel) || /^[A-Za-z]:/.test(rel)) {
    // Different drive on Windows: fall back to an absolute file URI.
    return 'file:///' + encodeUriPath(toPosix(program).replace(/^\//, ''));
  }
  return encodeUriPath(toPosix(rel));
}

export interface RenderOptions {
  targetImport: string;
  /** Default proxy port baked into the entry (plain-Dart sessions); Flutter sessions use the dart-define. */
  proxyPort: number;
  /** PEM certificate of this install's CA (never the private key). */
  caCertPem: string;
}

/** `--dart-define` name carrying `<host>:<port>` for Flutter sessions (CONTRACTS §1/§2). */
export const PROXY_DEFINE = 'FLUTTER_INTERCEPT_PROXY';
/** CONTRACTS §9.1: request header carrying the opaque trace id (the proxy strips it before upstream). */
export const TRACE_HEADER = 'x-fi-id';
/** CONTRACTS §9.1: where the entry posts `{"traces":[{"id","stack"}]}` (answered by the proxy only). */
export const TRACE_URL = 'https://trace.flutter-intercept.invalid/v1/traces';

/** Exactly one PEM certificate block, nothing else (it is embedded in a Dart raw string). */
export function normalizeCaCertPem(pem: string): string {
  const blocks = pem.match(/-----BEGIN CERTIFICATE-----[A-Za-z0-9+/=\s]+?-----END CERTIFICATE-----/g) ?? [];
  if (blocks.length !== 1) throw new Error(`expected exactly one PEM certificate, got ${blocks.length}`);
  return blocks[0].replace(/\r\n?/g, '\n').trim();
}

/**
 * Renders the entry. An empty `caCertPem` leaves the CA placeholder in place: such a plan is only
 * used to decide whether a launch is intercepted, and `writeEntry` refuses to write it.
 */
export function renderEntry(opts: RenderOptions): string {
  const out = ENTRY_TEMPLATE
    .replace('{{TARGET_IMPORT}}', opts.targetImport.replace(/'/g, "\\'"))
    .replace('{{PROXY_PORT}}', String(opts.proxyPort));
  if (!opts.caCertPem) return out;
  const ca = normalizeCaCertPem(opts.caCertPem);
  return out.replace('{{CA_CERT_PEM}}', () => ca + '\n');
}

/** First 12 hex chars of sha1(entry bytes), for `--dart-define=FLUTTER_INTERCEPT_ENTRY_SHA=` (CONTRACTS §1). */
export function entrySha(content: string): string {
  return crypto.createHash('sha1').update(Buffer.from(content, 'utf8')).digest('hex').slice(0, 12);
}

export interface EntryPlanInput {
  /** Absolute path of the app's real entry point (already resolved). */
  program: string;
  /** Fallback root when no pubspec.yaml is found above the program (cwd or workspace folder). */
  fallbackRoot?: string;
  proxyPort: number;
  caCertPem: string;
}

export interface EntryPlan {
  projectRoot: string;
  packageName?: string;
  isFlutter: boolean;
  program: string;
  entryPath: string;
  targetImport: string;
  content: string;
  /** entrySha(content) */
  sha: string;
}

export function planEntry(input: EntryPlanInput, f: FsLike = realFs): EntryPlan | undefined {
  const program = path.resolve(input.program);
  const projectRoot = findPubspecRoot(program, f) ?? input.fallbackRoot;
  if (!projectRoot) return undefined;
  const pubspec = readPubspec(projectRoot, f);
  const entryPath = entryPathFor(projectRoot, program);
  const targetImport = targetImportFor(projectRoot, pubspec.name, program, entryPath);
  const content = renderEntry({ targetImport, proxyPort: input.proxyPort, caCertPem: input.caCertPem });
  return { projectRoot, packageName: pubspec.name, isFlutter: pubspec.isFlutter, program, entryPath, targetImport, content, sha: entrySha(content) };
}

/** Writes the planned entry (creating the directory). Only rewrites when content changed. */
export async function writeEntry(plan: EntryPlan): Promise<void> {
  if (plan.content.includes('{{CA_CERT_PEM}}')) throw new Error('refusing to write an entry without the CA certificate');
  await fs.promises.mkdir(path.dirname(plan.entryPath), { recursive: true });
  try {
    const existing = await fs.promises.readFile(plan.entryPath, 'utf8');
    if (existing === plan.content) return;
  } catch {
    // does not exist yet
  }
  await fs.promises.writeFile(plan.entryPath, plan.content, 'utf8');
}
