/**
 * Dart model emitters (CONTRACTS §10.4). Pure: `generateModels` returns one file per root
 * (`lib/models/<root>.dart`) with every nested class in it, formatted like `dart format` (tall style).
 *
 * - `freezed`: freezed 3 (`@freezed abstract class X with _$X`, `const factory`, `fromJson` factory) and
 *   `part` lines for `.freezed.dart` / `.g.dart`.
 * - `json_serializable`: `@JsonSerializable()` classes with final fields and `fromJson` / `toJson` delegating
 *   to the generated `_$XFromJson` / `_$XToJson`.
 * - `plain`: hand-written `fromJson` / `toJson` with the casts `jsonDecode` output needs (num → double …).
 * Keys that aren't the field name get `@JsonKey(name: …)`; a field missing from some samples (but never null)
 * gets `includeIfNull: false` so `toJson` keeps the wire shape; classes with nested models use
 * `explicitToJson: true` so `toJson` returns plain maps all the way down.
 */
import { dartString } from './snippets';
import { dartTypeName, inferSchema, type ClassDef, type DartType, type FieldDef, type Schema } from './infer';
import { snakeCase } from './naming';
import { commentText } from './text';
import type { GeneratedFile, ModelGenInput, ModelStyle } from './types';

export function generateModels(input: ModelGenInput): GeneratedFile[] {
  const schema = inferSchema(input.samples, input.rootName);
  return [emitModelFile(schema, input.style, { source: input.source, samples: input.samples.length })];
}

export function emitModelFile(schema: Schema, style: ModelStyle, meta: { source?: string; samples: number }): GeneratedFile {
  const base = snakeCase(schema.rootName) || 'model';
  const lines: string[] = [];
  const n = meta.samples;
  const from = `from ${n} recorded response${n === 1 ? '' : 's'}`;
  if (meta.source) lines.push(`// Generated by Flutter Intercept ${from}`, `// of ${commentText(meta.source)}.`);
  else lines.push(`// Generated by Flutter Intercept ${from}.`);
  if (schema.rootType.kind !== 'class') {
    lines.push(
      `// The response is a ${dartTypeName(schema.rootType)}; decode it with:`,
      `//   ${decode(schema.rootType, 'jsonDecode(body)', 0)}`,
    );
  }
  const keyed = schema.classes.some((c) => c.fields.some((f) => jsonKeyArgs(f).length));
  if (style === 'freezed' && keyed) lines.push('// ignore_for_file: invalid_annotation_target');
  const parts = [lines.join('\n')];
  if (style === 'freezed') {
    parts.push("import 'package:freezed_annotation/freezed_annotation.dart';", `part '${base}.freezed.dart';\npart '${base}.g.dart';`);
  } else if (style === 'json_serializable') {
    parts.push("import 'package:json_annotation/json_annotation.dart';", `part '${base}.g.dart';`);
  }
  for (const c of schema.classes) {
    parts.push(style === 'freezed' ? freezedClass(c) : style === 'json_serializable' ? jsonSerializableClass(c) : plainClass(c));
  }
  return { path: `lib/models/${base}.dart`, content: parts.join('\n\n') + '\n' };
}

/** `sig => body;` on one line when it fits in 80 columns, else with the body on the next line (+4). */
function arrow(indent: string, sig: string, body: string): string[] {
  const one = `${indent}${sig} => ${body};`;
  return one.length <= 80 ? [one] : [`${indent}${sig} =>`, `${indent}    ${body};`];
}

/** `name: 'avatar_url'`, `includeIfNull: false` … for a field's @JsonKey. */
function jsonKeyArgs(f: FieldDef): string[] {
  const args: string[] = [];
  if (f.key !== f.name) args.push(`name: ${dartString(f.key)}`);
  if (f.optional && !f.nullable && f.type.kind !== 'dynamic') args.push('includeIfNull: false');
  return args;
}

function docLine(f: FieldDef): string | undefined {
  if (f.optional && f.nullable) return '/// Missing or null in some samples.';
  if (f.optional) return '/// Missing from some samples.';
  if (f.nullable) return '/// null in some samples.';
  return undefined;
}

function hasNested(c: ClassDef): boolean {
  const nested = (t: DartType): boolean => t.kind === 'class' || ((t.kind === 'list' || t.kind === 'map') && nested(t.of));
  return c.fields.some((f) => nested(f.type));
}

const isNullable = (t: DartType) => t.kind === 'dynamic' || t.nullable;

// ------------------------------------------------------------------ freezed

function freezedClass(c: ClassDef): string {
  const out: string[] = [];
  out.push('@freezed', `abstract class ${c.name} with _$${c.name} {`);
  // json_serializable options go on the factory constructor for freezed classes.
  if (hasNested(c)) out.push('  @JsonSerializable(explicitToJson: true)');
  const params = c.fields.map((f) => {
    const args = jsonKeyArgs(f);
    const ann = args.length ? `@JsonKey(${args.join(', ')}) ` : '';
    return { doc: docLine(f), text: `${ann}${isNullable(f.type) ? '' : 'required '}${dartTypeName(f.type)} ${f.name}` };
  });
  const head = `  const factory ${c.name}(`;
  const tail = `) = _${c.name};`;
  const flat = params.length ? `{${params.map((p) => p.text).join(', ')}}` : '';
  if (!params.some((p) => p.doc) && (head + flat + tail).length <= 80) out.push(head + flat + tail);
  else if (!params.some((p) => p.doc) && (head + flat + ') =').length <= 80) out.push(head + flat + ') =', `      _${c.name};`);
  else {
    out.push(`  const factory ${c.name}({`);
    params.forEach((p, i) => {
      if (p.doc && i > 0) out.push('');
      if (p.doc) out.push(`    ${p.doc}`);
      out.push(`    ${p.text},`);
    });
    out.push(`  }) = _${c.name};`);
  }
  out.push('', ...arrow('  ', `factory ${c.name}.fromJson(Map<String, dynamic> json)`, `_$${c.name}FromJson(json)`), '}');
  return out.join('\n');
}

// ------------------------------------------------------------------ json_serializable

function constructor(c: ClassDef): string[] {
  const params = c.fields.map((f) => `${isNullable(f.type) ? '' : 'required '}this.${f.name}`);
  const flat = `  const ${c.name}(${params.length ? `{${params.join(', ')}}` : ''});`;
  if (flat.length <= 80) return [flat];
  return [`  const ${c.name}({`, ...params.map((p) => `    ${p},`), '  });'];
}

/** Field declarations; annotated / documented ones get a blank line around them, like `dart format` keeps. */
function fieldDecls(c: ClassDef, annotate: boolean): string[] {
  const out: string[] = [];
  for (const f of c.fields) {
    const doc = docLine(f);
    const args = annotate ? jsonKeyArgs(f) : [];
    const block = !!(doc || args.length);
    if (out.length && block && out[out.length - 1] !== '') out.push('');
    if (doc) out.push(`  ${doc}`);
    if (args.length) out.push(`  @JsonKey(${args.join(', ')})`);
    out.push(`  final ${dartTypeName(f.type)} ${f.name};`);
    if (block) out.push('');
  }
  while (out[out.length - 1] === '') out.pop();
  return out;
}

function jsonSerializableClass(c: ClassDef): string {
  const out = [hasNested(c) ? '@JsonSerializable(explicitToJson: true)' : '@JsonSerializable()', `class ${c.name} {`];
  out.push(...constructor(c), '');
  out.push(...arrow('  ', `factory ${c.name}.fromJson(Map<String, dynamic> json)`, `_$${c.name}FromJson(json)`), '');
  const decls = fieldDecls(c, true);
  if (decls.length) out.push(...decls, '');
  out.push(...arrow('  ', 'Map<String, dynamic> toJson()', `_$${c.name}ToJson(this)`), '}');
  return out.join('\n');
}

// ------------------------------------------------------------------ plain

/** Dart expression turning `e` (a `dynamic` from jsonDecode) into type `t`. */
export function decode(t: DartType, e: string, depth: number): string {
  const v = depth ? `e${depth}` : 'e';
  const q = isNullable(t) ? '?' : '';
  switch (t.kind) {
    case 'dynamic':
      return e;
    case 'double':
      return q ? `(${e} as num?)?.toDouble()` : `(${e} as num).toDouble()`;
    case 'int':
    case 'bool':
    case 'String':
      return `${e} as ${t.kind}${q}`;
    case 'class':
      return q ? `${e} == null ? null : ${t.name}.fromJson(${e} as Map<String, dynamic>)` : `${t.name}.fromJson(${e} as Map<String, dynamic>)`;
    case 'list': {
      const inner = decode(t.of, v, depth + 1);
      if (inner === v) return `${e} as List<dynamic>${q}`;
      return `(${e} as List<dynamic>${q})${q ? '?' : ''}.map((${v}) => ${inner}).toList()`;
    }
    case 'map': {
      const inner = decode(t.of, v, depth + 1);
      if (inner === v) return `${e} as Map<String, dynamic>${q}`;
      const k = depth ? `k${depth}` : 'k';
      return `(${e} as Map<String, dynamic>${q})${q ? '?' : ''}.map((${k}, ${v}) => MapEntry(${k}, ${inner}))`;
    }
  }
}

/** Dart expression turning field value `x` of type `t` into JSON-encodable data. */
export function encode(t: DartType, x: string, depth: number): string {
  const v = depth ? `e${depth}` : 'e';
  const q = isNullable(t) ? '?' : '';
  switch (t.kind) {
    case 'class':
      return `${x}${q}.toJson()`;
    case 'list': {
      const inner = encode(t.of, v, depth + 1);
      return inner === v ? x : `${x}${q}.map((${v}) => ${inner}).toList()`;
    }
    case 'map': {
      const inner = encode(t.of, v, depth + 1);
      const k = depth ? `k${depth}` : 'k';
      return inner === v ? x : `${x}${q}.map((${k}, ${v}) => MapEntry(${k}, ${inner}))`;
    }
    default:
      return x;
  }
}

/**
 * One `name: expression,` entry, wrapped roughly like `dart format` when longer than 80 columns:
 * `.map(…)` / `.toList()` chains and `== null ? … : …` go on their own lines.
 */
function entry(indent: string, label: string, expr: string): string[] {
  const one = `${indent}${label}${expr},`;
  if (one.length <= 80) return [one];
  const cont = indent + '    ';
  const ternary = /^(.+?) == null \? null : (.+)$/.exec(expr);
  if (ternary && !ternary[1].includes(' ')) return [`${indent}${label}${ternary[1]} == null`, `${cont}? null`, `${cont}: ${ternary[2]},`];
  const chain = /^(\(.+? as (?:List|Map)<[^()]*>\??\))(\??\.map\(.+?\))(\.toList\(\))?$/.exec(expr);
  if (chain) return [`${indent}${label}${chain[1]}`, `${cont}${chain[2]}`, ...(chain[3] ? [`${cont}${chain[3]}`] : []), ].map((l, i, all) => (i === all.length - 1 ? l + ',' : l));
  return [one];
}

function plainClass(c: ClassDef): string {
  const out = [`class ${c.name} {`, ...constructor(c), ''];
  if (!c.fields.length) out.push(...arrow('  ', `factory ${c.name}.fromJson(Map<String, dynamic> json)`, `const ${c.name}()`));
  else {
    const args = c.fields.map((f) => [`${f.name}: `, decode(f.type, `json[${dartString(f.key)}]`, 0)] as const);
    const call = `${c.name}(${args.map(([l, e]) => l + e).join(', ')})`;
    if (`      ${call};`.length <= 80) out.push(...arrow('  ', `factory ${c.name}.fromJson(Map<String, dynamic> json)`, call));
    else {
      const head = `  factory ${c.name}.fromJson(Map<String, dynamic> json) => ${c.name}(`;
      const deep = head.length > 80; // the formatter then moves the call to its own line
      if (deep) out.push(`  factory ${c.name}.fromJson(Map<String, dynamic> json) =>`, `      ${c.name}(`);
      else out.push(head);
      for (const [label, e] of args) out.push(...entry(deep ? '        ' : '    ', label, e));
      out.push(deep ? '      );' : '  );');
    }
  }
  out.push('');
  const decls = fieldDecls(c, false);
  if (decls.length) out.push(...decls, '');
  const entries = c.fields.map((f) => {
    const e = `${dartString(f.key)}: ${encode(f.type, f.name, 0)}`;
    return f.optional && !f.nullable && f.type.kind !== 'dynamic' ? `if (${f.name} != null) ${e}` : e;
  });
  const flat = `  Map<String, dynamic> toJson() => {${entries.join(', ')}};`;
  if (flat.length <= 80) out.push(flat);
  else out.push('  Map<String, dynamic> toJson() => {', ...entries.flatMap((e) => entry('    ', '', e)), '  };');
  out.push('}');
  return out.join('\n');
}
